name: JayEpsteinJazz
favicon: null
layout_spectrum: 0.8258216802496463
typography_spectrum: 0.4705063016153872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7637520779389888
  lightness: 0.10148267121985555
  saturation: 0.39158546924591064
  rhythmicContrast: 0.20600419957190752
purpose: []
